import nodemailer from "nodemailer";

export async function POST(req) {
  try {
    const data = await req.json();

    const {
      firstName,
      lastName,
      email,
      phone,
      country,
      cabana,
      adults,
      children,
      checkIn,
      checkOut,
      meals,
      notes,
    } = data;

    // IMPORTANT: Replace with your actual live domain (e.g., https://naturewinyala.com)
    const domain = process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";
    const logoUrl = `${domain}/assets/images/LogoVersion2.png`;
    // Please replace the logo path as well if necessary

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    const htmlTemplate = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; }
          .container { max-width: 600px; margin: 20px auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden; }
          .header { background-color: #1a3a32; color: #ffffff; padding: 30px; text-align: center; }
          .logo { width: 120px; height: auto; margin-bottom: 15px; }
          .header h1 { margin: 0; font-size: 20px; letter-spacing: 2px; text-transform: uppercase; font-weight: 300; }
          .content { padding: 30px; background-color: #ffffff; }
          .section-title { color: #1a3a32; font-size: 16px; border-bottom: 2px solid #f0f0f0; padding-bottom: 8px; margin-bottom: 20px; font-weight: bold; text-transform: uppercase; }
          .info-item { margin-bottom: 15px; }
          .label { font-weight: bold; color: #888; font-size: 11px; text-transform: uppercase; display: block; margin-bottom: 2px; }
          .value { font-size: 15px; color: #1a3a32; }
          .highlight { background-color: #f7f9f8; padding: 20px; border-radius: 6px; border: 1px dashed #1a3a32; margin: 20px 0; }
          .footer { background-color: #f9f9f9; padding: 20px; text-align: center; font-size: 11px; color: #999; border-top: 1px solid #eeeeee; line-height: 1.8; }
          .footer strong { color: #666; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <img src="${logoUrl}" alt="Nature Win Yala Logo" class="logo" />
            <h1>New Booking Request</h1>
          </div>
          
          <div class="content">
            <div class="section-title">Guest Details</div>
            <div class="info-item">
              <span class="label">Full Name</span>
              <span class="value">${firstName} ${lastName}</span>
            </div>
            <div style="display: flex;">
               <div class="info-item" style="flex: 1;">
                <span class="label">Email</span>
                <span class="value">${email}</span>
              </div>
              <div class="info-item" style="flex: 1;">
                <span class="label">Phone</span>
                <span class="value">${phone}</span>
              </div>
            </div>
            <div class="info-item">
              <span class="label">Country of Origin</span>
              <span class="value">${country}</span>
            </div>

            <div class="section-title" style="margin-top: 30px;">Reservation Summary</div>
            <div class="highlight">
              <div class="info-item">
                <span class="label">Accomodation</span>
                <span class="value" style="font-size: 18px;"><strong>${cabana}</strong></span>
              </div>
              <div class="info-item">
                <span class="label">Stay Dates</span>
                <span class="value">${checkIn} — ${checkOut}</span>
              </div>
              <div class="info-item">
                <span class="label">Travelers</span>
                <span class="value">${adults} Adults, ${children} Children</span>
              </div>
            </div>

            <div class="section-title">Additional Info</div>
            <div class="info-item">
              <span class="label">Meal Preferences</span>
              <span class="value">${meals.length > 0 ? meals.join(", ") : "None selected"}</span>
            </div>
            <div class="info-item">
              <span class="label">Special Notes</span>
              <p class="value" style="background: #fff9e6; padding: 10px; border-radius: 4px; border-left: 3px solid #f39c12;">
                ${notes || "No special requests."}
              </p>
            </div>
          </div>

          <div class="footer">
            <p>© ${new Date().getFullYear()} Nature Win Yala. All rights reserved.</p>
            <p>This email was generated by <strong>Syntrix Mail Service</strong> using <strong>Nodemailer</strong> via the Nature Win Yala Booking Engine.</p>
          </div>
        </div>
      </body>
      </html>
    `;

    const mailOptions = {
      from: `"Nature Win Yala Booking" <${process.env.EMAIL_USER}>`,
      to: process.env.OWNER_EMAIL,
      subject: `New Request: ${firstName} ${lastName} (${cabana})`,
      html: htmlTemplate,
    };

    await transporter.sendMail(mailOptions);

    return Response.json({ success: true });
  } catch (error) {
    console.error(error);
    return Response.json({ success: false }, { status: 500 });
  }
}